-- 00 - Ejecutar primero. Carga partidos oficiales desde ANALISIS_corregido.xlsx.
with corrected_matches(id, match_number, phase, group_name, team_a, team_b, sort_order) as (
  values
    (1, 1, 'Fase de grupos', 'Grupo A', 'Mexico', 'Sudafrica', 1),
    (2, 2, 'Fase de grupos', 'Grupo A', 'Corea del Sur', 'Republica Checa', 2),
    (3, 3, 'Fase de grupos', 'Grupo A', 'Mexico', 'Corea del Sur', 3),
    (4, 4, 'Fase de grupos', 'Grupo A', 'Republica Checa', 'Sudafrica', 4),
    (5, 5, 'Fase de grupos', 'Grupo A', 'Republica Checa', 'Mexico', 5),
    (6, 6, 'Fase de grupos', 'Grupo A', 'Sudafrica', 'Corea del Sur', 6),
    (7, 7, 'Fase de grupos', 'Grupo B', 'Canada', 'Suiza', 7),
    (8, 8, 'Fase de grupos', 'Grupo B', 'Qatar', 'Bosnia y Herzegovina', 8),
    (9, 9, 'Fase de grupos', 'Grupo B', 'Canada', 'Qatar', 9),
    (10, 10, 'Fase de grupos', 'Grupo B', 'Bosnia y Herzegovina', 'Suiza', 10),
    (11, 11, 'Fase de grupos', 'Grupo B', 'Bosnia y Herzegovina', 'Canada', 11),
    (12, 12, 'Fase de grupos', 'Grupo B', 'Suiza', 'Qatar', 12),
    (13, 13, 'Fase de grupos', 'Grupo C', 'Brasil', 'Marruecos', 13),
    (14, 14, 'Fase de grupos', 'Grupo C', 'Haiti', 'Escocia', 14),
    (15, 15, 'Fase de grupos', 'Grupo C', 'Brasil', 'Haiti', 15),
    (16, 16, 'Fase de grupos', 'Grupo C', 'Escocia', 'Marruecos', 16),
    (17, 17, 'Fase de grupos', 'Grupo C', 'Escocia', 'Brasil', 17),
    (18, 18, 'Fase de grupos', 'Grupo C', 'Marruecos', 'Haiti', 18),
    (19, 19, 'Fase de grupos', 'Grupo D', 'Estados Unidos', 'Paraguay', 19),
    (20, 20, 'Fase de grupos', 'Grupo D', 'Australia', 'Turquia', 20),
    (21, 21, 'Fase de grupos', 'Grupo D', 'Estados Unidos', 'Australia', 21),
    (22, 22, 'Fase de grupos', 'Grupo D', 'Turquia', 'Paraguay', 22),
    (23, 23, 'Fase de grupos', 'Grupo D', 'Turquia', 'Estados Unidos', 23),
    (24, 24, 'Fase de grupos', 'Grupo D', 'Paraguay', 'Australia', 24),
    (25, 25, 'Fase de grupos', 'Grupo E', 'Alemania', 'Curazao', 25),
    (26, 26, 'Fase de grupos', 'Grupo E', 'Costa de Marfil', 'Ecuador', 26),
    (27, 27, 'Fase de grupos', 'Grupo E', 'Alemania', 'Costa de Marfil', 27),
    (28, 28, 'Fase de grupos', 'Grupo E', 'Ecuador', 'Curazao', 28),
    (29, 29, 'Fase de grupos', 'Grupo E', 'Ecuador', 'Alemania', 29),
    (30, 30, 'Fase de grupos', 'Grupo E', 'Curazao', 'Costa de Marfil', 30),
    (31, 31, 'Fase de grupos', 'Grupo F', 'Paises Bajos', 'Japon', 31),
    (32, 32, 'Fase de grupos', 'Grupo F', 'Tunez', 'Suecia', 32),
    (33, 33, 'Fase de grupos', 'Grupo F', 'Paises Bajos', 'Tunez', 33),
    (34, 34, 'Fase de grupos', 'Grupo F', 'Suecia', 'Japon', 34),
    (35, 35, 'Fase de grupos', 'Grupo F', 'Suecia', 'Paises Bajos', 35),
    (36, 36, 'Fase de grupos', 'Grupo F', 'Japon', 'Tunez', 36),
    (37, 37, 'Fase de grupos', 'Grupo G', 'Belgica', 'Egipto', 37),
    (38, 38, 'Fase de grupos', 'Grupo G', 'Iran', 'Nueva Zelanda', 38),
    (39, 39, 'Fase de grupos', 'Grupo G', 'Belgica', 'Iran', 39),
    (40, 40, 'Fase de grupos', 'Grupo G', 'Nueva Zelanda', 'Egipto', 40),
    (41, 41, 'Fase de grupos', 'Grupo G', 'Nueva Zelanda', 'Belgica', 41),
    (42, 42, 'Fase de grupos', 'Grupo G', 'Egipto', 'Iran', 42),
    (43, 43, 'Fase de grupos', 'Grupo H', 'Espana', 'Cabo Verde', 43),
    (44, 44, 'Fase de grupos', 'Grupo H', 'Arabia Saudita', 'Uruguay', 44),
    (45, 45, 'Fase de grupos', 'Grupo H', 'Espana', 'Arabia Saudita', 45),
    (46, 46, 'Fase de grupos', 'Grupo H', 'Uruguay', 'Cabo Verde', 46),
    (47, 47, 'Fase de grupos', 'Grupo H', 'Uruguay', 'Espana', 47),
    (48, 48, 'Fase de grupos', 'Grupo H', 'Cabo Verde', 'Arabia Saudita', 48),
    (49, 49, 'Fase de grupos', 'Grupo I', 'Francia', 'Senegal', 49),
    (50, 50, 'Fase de grupos', 'Grupo I', 'Noruega', 'Irak', 50),
    (51, 51, 'Fase de grupos', 'Grupo I', 'Francia', 'Noruega', 51),
    (52, 52, 'Fase de grupos', 'Grupo I', 'Irak', 'Senegal', 52),
    (53, 53, 'Fase de grupos', 'Grupo I', 'Irak', 'Francia', 53),
    (54, 54, 'Fase de grupos', 'Grupo I', 'Senegal', 'Noruega', 54),
    (55, 55, 'Fase de grupos', 'Grupo J', 'Argentina', 'Argelia', 55),
    (56, 56, 'Fase de grupos', 'Grupo J', 'Austria', 'Jordania', 56),
    (57, 57, 'Fase de grupos', 'Grupo J', 'Argentina', 'Austria', 57),
    (58, 58, 'Fase de grupos', 'Grupo J', 'Jordania', 'Argelia', 58),
    (59, 59, 'Fase de grupos', 'Grupo J', 'Jordania', 'Argentina', 59),
    (60, 60, 'Fase de grupos', 'Grupo J', 'Argelia', 'Austria', 60),
    (61, 61, 'Fase de grupos', 'Grupo K', 'Portugal', 'Uzbekistan', 61),
    (62, 62, 'Fase de grupos', 'Grupo K', 'Colombia', 'RD Congo', 62),
    (63, 63, 'Fase de grupos', 'Grupo K', 'Portugal', 'Colombia', 63),
    (64, 64, 'Fase de grupos', 'Grupo K', 'RD Congo', 'Uzbekistan', 64),
    (65, 65, 'Fase de grupos', 'Grupo K', 'RD Congo', 'Portugal', 65),
    (66, 66, 'Fase de grupos', 'Grupo K', 'Uzbekistan', 'Colombia', 66),
    (67, 67, 'Fase de grupos', 'Grupo L', 'Inglaterra', 'Croacia', 67),
    (68, 68, 'Fase de grupos', 'Grupo L', 'Ghana', 'Panama', 68),
    (69, 69, 'Fase de grupos', 'Grupo L', 'Inglaterra', 'Ghana', 69),
    (70, 70, 'Fase de grupos', 'Grupo L', 'Panama', 'Croacia', 70),
    (71, 71, 'Fase de grupos', 'Grupo L', 'Panama', 'Inglaterra', 71),
    (72, 72, 'Fase de grupos', 'Grupo L', 'Croacia', 'Ghana', 72)
)
insert into public.matches(id, match_number, phase, group_name, team_a, team_b, sort_order, match_date, venue, status)
select id, match_number, phase, group_name, team_a, team_b, sort_order, null::timestamptz, null::text, 'scheduled'::public.match_status
from corrected_matches
on conflict (id) do update set
  match_number = excluded.match_number,
  phase = excluded.phase,
  group_name = excluded.group_name,
  team_a = excluded.team_a,
  team_b = excluded.team_b,
  sort_order = excluded.sort_order,
  match_date = null,
  venue = null;
