-- Repara el mapeo interno de partidos.
-- IMPORTANTE: no modifica prediction_details ni results.
-- Los pronosticos y resultados oficiales ya fueron ingresados siguiendo el orden visible en pantalla.

update public.matches m
set
  phase = v.phase,
  group_name = v.group_name,
  team_a = v.team_a,
  team_b = v.team_b,
  sort_order = v.sort_order
from (
  values
  (1, 'Fase de grupos', 'Grupo A', 'Mexico', 'Sudafrica', 1),
  (2, 'Fase de grupos', 'Grupo A', 'Corea del Sur', 'Republica Checa', 2),
  (3, 'Fase de grupos', 'Grupo A', 'Mexico', 'Corea del Sur', 3),
  (4, 'Fase de grupos', 'Grupo A', 'Republica Checa', 'Sudafrica', 4),
  (5, 'Fase de grupos', 'Grupo A', 'Republica Checa', 'Mexico', 5),
  (6, 'Fase de grupos', 'Grupo A', 'Sudafrica', 'Corea del Sur', 6),
  (7, 'Fase de grupos', 'Grupo B', 'Canada', 'Suiza', 7),
  (8, 'Fase de grupos', 'Grupo B', 'Qatar', 'Bosnia y Herzegovina', 8),
  (9, 'Fase de grupos', 'Grupo B', 'Canada', 'Qatar', 9),
  (10, 'Fase de grupos', 'Grupo B', 'Bosnia y Herzegovina', 'Suiza', 10),
  (11, 'Fase de grupos', 'Grupo B', 'Bosnia y Herzegovina', 'Canada', 11),
  (12, 'Fase de grupos', 'Grupo B', 'Suiza', 'Qatar', 12),
  (13, 'Fase de grupos', 'Grupo C', 'Brasil', 'Marruecos', 13),
  (14, 'Fase de grupos', 'Grupo C', 'Haiti', 'Escocia', 14),
  (15, 'Fase de grupos', 'Grupo C', 'Brasil', 'Haiti', 15),
  (16, 'Fase de grupos', 'Grupo C', 'Escocia', 'Marruecos', 16),
  (17, 'Fase de grupos', 'Grupo C', 'Escocia', 'Brasil', 17),
  (18, 'Fase de grupos', 'Grupo C', 'Marruecos', 'Haiti', 18),
  (19, 'Fase de grupos', 'Grupo D', 'Estados Unidos', 'Paraguay', 19),
  (20, 'Fase de grupos', 'Grupo D', 'Australia', 'Turquia', 20),
  (21, 'Fase de grupos', 'Grupo D', 'Estados Unidos', 'Australia', 21),
  (22, 'Fase de grupos', 'Grupo D', 'Turquia', 'Paraguay', 22),
  (23, 'Fase de grupos', 'Grupo D', 'Turquia', 'Estados Unidos', 23),
  (24, 'Fase de grupos', 'Grupo D', 'Paraguay', 'Australia', 24),
  (25, 'Fase de grupos', 'Grupo E', 'Alemania', 'Curazao', 25),
  (26, 'Fase de grupos', 'Grupo E', 'Costa de Marfil', 'Ecuador', 26),
  (27, 'Fase de grupos', 'Grupo E', 'Alemania', 'Costa de Marfil', 27),
  (28, 'Fase de grupos', 'Grupo E', 'Ecuador', 'Curazao', 28),
  (29, 'Fase de grupos', 'Grupo E', 'Ecuador', 'Alemania', 29),
  (30, 'Fase de grupos', 'Grupo E', 'Curazao', 'Costa de Marfil', 30),
  (31, 'Fase de grupos', 'Grupo F', 'Paises Bajos', 'Japon', 31),
  (32, 'Fase de grupos', 'Grupo F', 'Tunez', 'Suecia', 32),
  (33, 'Fase de grupos', 'Grupo F', 'Paises Bajos', 'Tunez', 33),
  (34, 'Fase de grupos', 'Grupo F', 'Suecia', 'Japon', 34),
  (35, 'Fase de grupos', 'Grupo F', 'Suecia', 'Paises Bajos', 35),
  (36, 'Fase de grupos', 'Grupo F', 'Japon', 'Tunez', 36),
  (37, 'Fase de grupos', 'Grupo G', 'Belgica', 'Egipto', 37),
  (38, 'Fase de grupos', 'Grupo G', 'Iran', 'Nueva Zelanda', 38),
  (39, 'Fase de grupos', 'Grupo G', 'Belgica', 'Iran', 39),
  (40, 'Fase de grupos', 'Grupo G', 'Nueva Zelanda', 'Egipto', 40),
  (41, 'Fase de grupos', 'Grupo G', 'Nueva Zelanda', 'Belgica', 41),
  (42, 'Fase de grupos', 'Grupo G', 'Egipto', 'Iran', 42),
  (43, 'Fase de grupos', 'Grupo H', 'Espana', 'Cabo Verde', 43),
  (44, 'Fase de grupos', 'Grupo H', 'Arabia Saudita', 'Uruguay', 44),
  (45, 'Fase de grupos', 'Grupo H', 'Espana', 'Arabia Saudita', 45),
  (46, 'Fase de grupos', 'Grupo H', 'Uruguay', 'Cabo Verde', 46),
  (47, 'Fase de grupos', 'Grupo H', 'Uruguay', 'Espana', 47),
  (48, 'Fase de grupos', 'Grupo H', 'Cabo Verde', 'Arabia Saudita', 48),
  (49, 'Fase de grupos', 'Grupo I', 'Francia', 'Senegal', 49),
  (50, 'Fase de grupos', 'Grupo I', 'Noruega', 'Irak', 50),
  (51, 'Fase de grupos', 'Grupo I', 'Francia', 'Noruega', 51),
  (52, 'Fase de grupos', 'Grupo I', 'Irak', 'Senegal', 52),
  (53, 'Fase de grupos', 'Grupo I', 'Irak', 'Francia', 53),
  (54, 'Fase de grupos', 'Grupo I', 'Senegal', 'Noruega', 54),
  (55, 'Fase de grupos', 'Grupo J', 'Argentina', 'Argelia', 55),
  (56, 'Fase de grupos', 'Grupo J', 'Austria', 'Jordania', 56),
  (57, 'Fase de grupos', 'Grupo J', 'Argentina', 'Austria', 57),
  (58, 'Fase de grupos', 'Grupo J', 'Jordania', 'Argelia', 58),
  (59, 'Fase de grupos', 'Grupo J', 'Jordania', 'Argentina', 59),
  (60, 'Fase de grupos', 'Grupo J', 'Argelia', 'Austria', 60),
  (61, 'Fase de grupos', 'Grupo K', 'Portugal', 'Uzbekistan', 61),
  (62, 'Fase de grupos', 'Grupo K', 'Colombia', 'RD Congo', 62),
  (63, 'Fase de grupos', 'Grupo K', 'Portugal', 'Colombia', 63),
  (64, 'Fase de grupos', 'Grupo K', 'RD Congo', 'Uzbekistan', 64),
  (65, 'Fase de grupos', 'Grupo K', 'RD Congo', 'Portugal', 65),
  (66, 'Fase de grupos', 'Grupo K', 'Uzbekistan', 'Colombia', 66),
  (67, 'Fase de grupos', 'Grupo L', 'Inglaterra', 'Croacia', 67),
  (68, 'Fase de grupos', 'Grupo L', 'Ghana', 'Panama', 68),
  (69, 'Fase de grupos', 'Grupo L', 'Inglaterra', 'Ghana', 69),
  (70, 'Fase de grupos', 'Grupo L', 'Panama', 'Croacia', 70),
  (71, 'Fase de grupos', 'Grupo L', 'Panama', 'Inglaterra', 71),
  (72, 'Fase de grupos', 'Grupo L', 'Croacia', 'Ghana', 72)
) as v(match_number, phase, group_name, team_a, team_b, sort_order)
where m.match_number = v.match_number;

select public.recalculate_rankings();
