-- Corrige el orden Equipo A / Equipo B en Supabase para que coincida con el fixture visible.
-- No modifica prediction_details ni results, porque esos goles ya fueron ingresados segun el orden visible.

update public.matches m
set
  team_a = v.team_a,
  team_b = v.team_b,
  venue = v.venue
from (
  values
  (1, 'Mexico', 'Sudafrica', 'Ciudad de Mexico'),
  (2, 'Corea del Sur', 'Republica Checa', 'Guadalajara'),
  (3, 'Canada', 'Bosnia y Herzegovina', 'Toronto'),
  (4, 'Estados Unidos', 'Paraguay', 'Los Angeles'),
  (5, 'Haiti', 'Escocia', 'Boston'),
  (6, 'Australia', 'Turquia', 'Vancouver'),
  (7, 'Brasil', 'Marruecos', 'Jersey'),
  (8, 'Qatar', 'Suiza', 'San Francisco'),
  (9, 'Costa de Marfil', 'Ecuador', 'Filadelfia'),
  (10, 'Alemania', 'Curazao', 'Houston'),
  (11, 'Paises Bajos', 'Japon', 'Dallas'),
  (12, 'Suecia', 'Tunez', 'Monterrey'),
  (13, 'Arabia Saudita', 'Uruguay', 'Miami'),
  (14, 'Espana', 'Cabo Verde', 'Atlanta'),
  (15, 'Iran', 'Nueva Zelanda', 'Los Angeles'),
  (16, 'Belgica', 'Egipto', 'Seattle'),
  (17, 'Francia', 'Senegal', 'N. York/N. Jersey'),
  (18, 'Irak', 'Noruega', 'Boston'),
  (19, 'Argentina', 'Argelia', 'Kansas City'),
  (20, 'Austria', 'Jordania', 'San Francisco'),
  (21, 'Ghana', 'Panama', 'Toronto'),
  (22, 'Inglaterra', 'Croacia', 'Dallas'),
  (23, 'Portugal', 'RD Congo', 'Houston'),
  (24, 'Uzbekistan', 'Colombia', 'Mexico'),
  (25, 'Republica Checa', 'Sudafrica', 'Atlanta'),
  (26, 'Suiza', 'Bosnia y Herzegovina', 'Los Angeles'),
  (27, 'Canada', 'Qatar', 'Vancouver'),
  (28, 'Mexico', 'Corea del Sur', 'Guadalajara'),
  (29, 'Brasil', 'Haiti', 'Filadelfia'),
  (30, 'Escocia', 'Marruecos', 'Boston'),
  (31, 'Turquia', 'Paraguay', 'San Francisco'),
  (32, 'Estados Unidos', 'Australia', 'Seattle'),
  (33, 'Alemania', 'Costa de Marfil', 'Toronto'),
  (34, 'Ecuador', 'Curazao', 'Kansas City'),
  (35, 'Paises Bajos', 'Suecia', 'Houston'),
  (36, 'Tunez', 'Japon', 'Monterrey'),
  (37, 'Uruguay', 'Cabo Verde', 'Miami'),
  (38, 'Espana', 'Arabia Saudita', 'Atlanta'),
  (39, 'Belgica', 'Iran', 'Los Angeles'),
  (40, 'Nueva Zelanda', 'Egipto', 'Vancouver'),
  (41, 'Noruega', 'Senegal', 'N. York/N. Jersey'),
  (42, 'Francia', 'Irak', 'Filadelfia'),
  (43, 'Argentina', 'Austria', 'Dallas'),
  (44, 'Jordania', 'Argelia', 'San Francisco'),
  (45, 'Inglaterra', 'Ghana', 'Boston'),
  (46, 'Panama', 'Croacia', 'Toronto'),
  (47, 'Portugal', 'Uzbekistan', 'Houston'),
  (48, 'Colombia', 'RD Congo', 'Guadalajara'),
  (49, 'Escocia', 'Brasil', 'Miami'),
  (50, 'Marruecos', 'Haiti', 'Atlanta'),
  (51, 'Suiza', 'Canada', 'Vancouver'),
  (52, 'Bosnia y Herzegovina', 'Qatar', 'Seattle'),
  (53, 'Republica Checa', 'Mexico', 'Ciudad de Mexico'),
  (54, 'Sudafrica', 'Corea del Sur', 'Monterrey'),
  (55, 'Curazao', 'Costa de Marfil', 'Filadelfia'),
  (56, 'Ecuador', 'Alemania', 'Jersey'),
  (57, 'Japon', 'Suecia', 'Dallas'),
  (58, 'Tunez', 'Paises Bajos', 'Kansas City'),
  (59, 'Turquia', 'Estados Unidos', 'Los Angeles'),
  (60, 'Paraguay', 'Australia', 'San Francisco'),
  (61, 'Noruega', 'Francia', 'Boston'),
  (62, 'Senegal', 'Irak', 'Toronto'),
  (63, 'Egipto', 'Iran', 'Seattle'),
  (64, 'Nueva Zelanda', 'Belgica', 'Vancouver'),
  (65, 'Cabo Verde', 'Arabia Saudita', 'Houston'),
  (66, 'Uruguay', 'Espana', 'Guadalajara'),
  (67, 'Panama', 'Inglaterra', 'N. York/N. Jersey'),
  (68, 'Croacia', 'Ghana', 'Filadelfia'),
  (69, 'Argelia', 'Austria', 'Kansas City'),
  (70, 'Jordania', 'Argentina', 'Dallas'),
  (71, 'Colombia', 'Portugal', 'Miami'),
  (72, 'RD Congo', 'Uzbekistan', 'Atlanta')
) as v(match_number, team_a, team_b, venue)
where m.match_number = v.match_number;

select public.recalculate_rankings();
