create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role' and typnamespace = 'public'::regnamespace) then
    create type public.app_role as enum ('user', 'admin');
  end if;
  if not exists (select 1 from pg_type where typname = 'prediction_status' and typnamespace = 'public'::regnamespace) then
    create type public.prediction_status as enum ('BORRADOR', 'CONFIRMADO', 'BLOQUEADO_POR_FECHA');
  end if;
  if not exists (select 1 from pg_type where typname = 'match_status' and typnamespace = 'public'::regnamespace) then
    create type public.match_status as enum ('scheduled', 'played');
  end if;
end $$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  role public.app_role not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_number int not null unique,
  phase text not null,
  group_name text,
  team_a text not null,
  team_b text not null,
  match_date timestamptz,
  venue text,
  status public.match_status not null default 'scheduled',
  sort_order int not null
);

create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  status public.prediction_status not null default 'BORRADOR',
  confirmed_at timestamptz,
  confirmation_code text unique,
  ip_address inet,
  user_agent text,
  validation_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.prediction_details (
  id uuid primary key default gen_random_uuid(),
  prediction_id uuid not null references public.predictions(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  predicted_goals_a int check (predicted_goals_a between 0 and 99),
  predicted_goals_b int check (predicted_goals_b between 0 and 99),
  points int not null default 0,
  exact_score boolean not null default false,
  winner_hit boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prediction_id, match_id)
);

create table if not exists public.results (
  id uuid primary key default gen_random_uuid(),
  match_id bigint not null unique references public.matches(id) on delete cascade,
  goals_a int not null check (goals_a between 0 and 99),
  goals_b int not null check (goals_b between 0 and 99),
  registered_by uuid references public.users(id),
  registered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rankings (
  user_id uuid primary key references public.users(id) on delete cascade,
  full_name text not null,
  total_points int not null default 0,
  exact_scores int not null default 0,
  winner_hits int not null default 0,
  matches_hit int not null default 0,
  position int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  user_id uuid references public.users(id),
  action text not null,
  entity text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create or replace view public.confirmed_predictions as
select u.full_name, p.confirmed_at, p.status::text as status
from public.predictions p
join public.users u on u.id = p.user_id
where p.status = 'CONFIRMADO'
order by p.confirmed_at desc;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.users where id = auth.uid() and role = 'admin');
$$;

create or replace function public.log_audit(p_action text, p_entity text, p_entity_id text default null, p_metadata jsonb default '{}'::jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
begin
  insert into public.audit_logs(user_id, action, entity, entity_id, metadata, ip_address, user_agent)
  values (
    auth.uid(),
    p_action,
    p_entity,
    p_entity_id,
    p_metadata,
    nullif(split_part(coalesce(headers->>'x-forwarded-for', ''), ',', 1), '')::inet,
    headers->>'user-agent'
  );
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users(id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.score_prediction(p_pred_a int, p_pred_b int, p_real_a int, p_real_b int)
returns table(points int, exact_score boolean, winner_hit boolean)
language sql
immutable
as $$
  select
    case
      when p_pred_a is null or p_pred_b is null or p_real_a is null or p_real_b is null then 0
      when p_pred_a = p_real_a and p_pred_b = p_real_b then 3
      when sign(p_pred_a - p_pred_b) = sign(p_real_a - p_real_b) then 1
      else 0
    end,
    p_pred_a = p_real_a and p_pred_b = p_real_b,
    not (p_pred_a = p_real_a and p_pred_b = p_real_b) and sign(p_pred_a - p_pred_b) = sign(p_real_a - p_real_b);
$$;

create or replace function public.recalculate_rankings()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.prediction_details pd
  set
    points = s.points,
    exact_score = s.exact_score,
    winner_hit = s.winner_hit,
    updated_at = now()
  from (
    select
      pd2.id,
      scored.points,
      scored.exact_score,
      scored.winner_hit
    from public.prediction_details pd2
    join public.results r on r.match_id = pd2.match_id
    cross join lateral public.score_prediction(pd2.predicted_goals_a, pd2.predicted_goals_b, r.goals_a, r.goals_b) scored
  ) s
  where s.id = pd.id;

  delete from public.rankings where true;

  insert into public.rankings(user_id, full_name, total_points, exact_scores, winner_hits, matches_hit, position, updated_at)
  select
    ranked.user_id,
    ranked.full_name,
    ranked.total_points,
    ranked.exact_scores,
    ranked.winner_hits,
    ranked.matches_hit,
    ranked.position,
    now()
  from (
    select
      u.id as user_id,
      u.full_name,
      coalesce(sum(pd.points), 0)::int as total_points,
      count(*) filter (where pd.exact_score)::int as exact_scores,
      count(*) filter (where pd.winner_hit)::int as winner_hits,
      count(*) filter (where pd.exact_score or pd.winner_hit)::int as matches_hit,
      row_number() over (
        order by coalesce(sum(pd.points), 0) desc,
        count(*) filter (where pd.exact_score) desc,
        count(*) filter (where pd.exact_score or pd.winner_hit) desc,
        u.full_name asc
      )::int as position
    from public.users u
    join public.predictions p on p.user_id = u.id and p.status = 'CONFIRMADO'
    left join public.prediction_details pd on pd.prediction_id = p.id
    group by u.id, u.full_name
  ) ranked;
end;
$$;

create sequence if not exists public.confirmation_code_seq start with 1;

create or replace function public.confirm_prediction(p_prediction_id uuid, p_user_agent text, p_validation_hash text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid;
  total_matches int;
  total_details int;
  next_code text;
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
begin
  select user_id into owner_id from public.predictions where id = p_prediction_id;
  if owner_id is null or owner_id <> auth.uid() then
    raise exception 'Pronostico no autorizado';
  end if;
  if now() >= (select value::timestamptz from public.settings where key = 'deadline_iso') then
    raise exception 'La fecha limite ya vencio';
  end if;
  select count(*) into total_matches from public.matches;
  select count(*) into total_details
  from public.prediction_details
  where prediction_id = p_prediction_id
    and predicted_goals_a is not null
    and predicted_goals_b is not null;
  if total_details <> total_matches then
    raise exception 'Debe completar todos los partidos antes de confirmar';
  end if;

  next_code := 'SEMAPA-2026-' || lpad(nextval('public.confirmation_code_seq')::text, 6, '0');

  update public.predictions
  set status = 'CONFIRMADO',
      confirmed_at = now(),
      confirmation_code = next_code,
      ip_address = nullif(split_part(coalesce(headers->>'x-forwarded-for', ''), ',', 1), '')::inet,
      user_agent = p_user_agent,
      validation_hash = p_validation_hash,
      updated_at = now()
  where id = p_prediction_id and status = 'BORRADOR';

  perform public.log_audit('CONFIRMACION_DEFINITIVA', 'predictions', p_prediction_id::text, jsonb_build_object('code', next_code));
  perform public.recalculate_rankings();
  return next_code;
end;
$$;

create or replace function public.register_result(p_match_id bigint, p_goals_a int, p_goals_b int)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Solo administradores';
  end if;
  insert into public.results(match_id, goals_a, goals_b, registered_by)
  values (p_match_id, p_goals_a, p_goals_b, auth.uid())
  on conflict (match_id) do update
  set goals_a = excluded.goals_a,
      goals_b = excluded.goals_b,
      registered_by = auth.uid(),
      updated_at = now();

  update public.matches set status = 'played' where id = p_match_id;
  perform public.log_audit('REGISTRO_RESULTADO', 'results', p_match_id::text, jsonb_build_object('goals_a', p_goals_a, 'goals_b', p_goals_b));
  perform public.recalculate_rankings();
end;
$$;

create or replace function public.admin_dashboard()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'registered', (select count(*) from public.users),
    'confirmed', (select count(*) from public.predictions where status = 'CONFIRMADO'),
    'pending', greatest((select count(*) from public.users) - (select count(*) from public.predictions where status = 'CONFIRMADO'), 0),
    'played', (select count(*) from public.matches where status = 'played'),
    'pending_matches', (select count(*) from public.matches where status <> 'played')
  )
  where public.is_admin();
$$;

alter table public.users enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;
alter table public.prediction_details enable row level security;
alter table public.results enable row level security;
alter table public.rankings enable row level security;
alter table public.settings enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "users read own or admin" on public.users;
drop policy if exists "users admin update" on public.users;
drop policy if exists "matches public read" on public.matches;
drop policy if exists "matches admin write" on public.matches;
drop policy if exists "predictions own read" on public.predictions;
drop policy if exists "predictions own draft insert" on public.predictions;
drop policy if exists "predictions own draft update" on public.predictions;
drop policy if exists "details own read" on public.prediction_details;
drop policy if exists "details own draft write" on public.prediction_details;
drop policy if exists "results read" on public.results;
drop policy if exists "results admin write" on public.results;
drop policy if exists "rankings read" on public.rankings;
drop policy if exists "settings read" on public.settings;
drop policy if exists "settings admin write" on public.settings;
drop policy if exists "audit admin read" on public.audit_logs;

create policy "users read own or admin" on public.users for select using (id = auth.uid() or public.is_admin());
create policy "users admin update" on public.users for update using (public.is_admin());

create policy "matches public read" on public.matches for select using (true);
create policy "matches admin write" on public.matches for all using (public.is_admin()) with check (public.is_admin());

create policy "predictions own read" on public.predictions for select using (user_id = auth.uid() or public.is_admin());
create policy "predictions own draft insert" on public.predictions for insert with check (user_id = auth.uid());
create policy "predictions own draft update" on public.predictions for update
using (user_id = auth.uid() and status = 'BORRADOR' and now() < (select value::timestamptz from public.settings where key = 'deadline_iso') or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy "details own read" on public.prediction_details for select
using (exists (select 1 from public.predictions p where p.id = prediction_id and (p.user_id = auth.uid() or public.is_admin())));
create policy "details own draft write" on public.prediction_details for all
using (exists (select 1 from public.predictions p where p.id = prediction_id and p.user_id = auth.uid() and p.status = 'BORRADOR' and now() < (select value::timestamptz from public.settings where key = 'deadline_iso')) or public.is_admin())
with check (exists (select 1 from public.predictions p where p.id = prediction_id and p.user_id = auth.uid() and p.status = 'BORRADOR') or public.is_admin());

create policy "results read" on public.results for select using (true);
create policy "results admin write" on public.results for all using (public.is_admin()) with check (public.is_admin());

create policy "rankings read" on public.rankings for select using (true);
create policy "settings read" on public.settings for select using (true);
create policy "settings admin write" on public.settings for all using (public.is_admin()) with check (public.is_admin());
create policy "audit admin read" on public.audit_logs for select using (public.is_admin());

insert into public.settings(key, value) values
  ('deadline_iso', '2026-06-11T13:00:00-04:00'),
  ('prizes_text', '1° Lugar\n2° Lugar\n3° Lugar')
on conflict (key) do nothing;

insert into public.matches(match_number, phase, group_name, team_a, team_b, sort_order)
select row_number() over (), phase, group_name, team_a, team_b, row_number() over ()
from (
  values
  ('Fase de grupos','Grupo A','Mexico','Sudafrica'),('Fase de grupos','Grupo A','Corea del Sur','Republica Checa'),('Fase de grupos','Grupo A','Mexico','Corea del Sur'),('Fase de grupos','Grupo A','Republica Checa','Sudafrica'),('Fase de grupos','Grupo A','Republica Checa','Mexico'),('Fase de grupos','Grupo A','Sudafrica','Corea del Sur'),
  ('Fase de grupos','Grupo B','Canada','Suiza'),('Fase de grupos','Grupo B','Qatar','Bosnia y Herzegovina'),('Fase de grupos','Grupo B','Canada','Qatar'),('Fase de grupos','Grupo B','Bosnia y Herzegovina','Suiza'),('Fase de grupos','Grupo B','Bosnia y Herzegovina','Canada'),('Fase de grupos','Grupo B','Suiza','Qatar'),
  ('Fase de grupos','Grupo C','Brasil','Marruecos'),('Fase de grupos','Grupo C','Haiti','Escocia'),('Fase de grupos','Grupo C','Brasil','Haiti'),('Fase de grupos','Grupo C','Escocia','Marruecos'),('Fase de grupos','Grupo C','Escocia','Brasil'),('Fase de grupos','Grupo C','Marruecos','Haiti'),
  ('Fase de grupos','Grupo D','Estados Unidos','Paraguay'),('Fase de grupos','Grupo D','Australia','Turquia'),('Fase de grupos','Grupo D','Estados Unidos','Australia'),('Fase de grupos','Grupo D','Turquia','Paraguay'),('Fase de grupos','Grupo D','Turquia','Estados Unidos'),('Fase de grupos','Grupo D','Paraguay','Australia'),
  ('Fase de grupos','Grupo E','Alemania','Curazao'),('Fase de grupos','Grupo E','Costa de Marfil','Ecuador'),('Fase de grupos','Grupo E','Alemania','Costa de Marfil'),('Fase de grupos','Grupo E','Ecuador','Curazao'),('Fase de grupos','Grupo E','Ecuador','Alemania'),('Fase de grupos','Grupo E','Curazao','Costa de Marfil'),
  ('Fase de grupos','Grupo F','Paises Bajos','Japon'),('Fase de grupos','Grupo F','Tunez','Suecia'),('Fase de grupos','Grupo F','Paises Bajos','Tunez'),('Fase de grupos','Grupo F','Suecia','Japon'),('Fase de grupos','Grupo F','Suecia','Paises Bajos'),('Fase de grupos','Grupo F','Japon','Tunez'),
  ('Fase de grupos','Grupo G','Belgica','Egipto'),('Fase de grupos','Grupo G','Iran','Nueva Zelanda'),('Fase de grupos','Grupo G','Belgica','Iran'),('Fase de grupos','Grupo G','Nueva Zelanda','Egipto'),('Fase de grupos','Grupo G','Nueva Zelanda','Belgica'),('Fase de grupos','Grupo G','Egipto','Iran'),
  ('Fase de grupos','Grupo H','Espana','Cabo Verde'),('Fase de grupos','Grupo H','Arabia Saudita','Uruguay'),('Fase de grupos','Grupo H','Espana','Arabia Saudita'),('Fase de grupos','Grupo H','Uruguay','Cabo Verde'),('Fase de grupos','Grupo H','Uruguay','Espana'),('Fase de grupos','Grupo H','Cabo Verde','Arabia Saudita'),
  ('Fase de grupos','Grupo I','Francia','Senegal'),('Fase de grupos','Grupo I','Noruega','Irak'),('Fase de grupos','Grupo I','Francia','Noruega'),('Fase de grupos','Grupo I','Irak','Senegal'),('Fase de grupos','Grupo I','Irak','Francia'),('Fase de grupos','Grupo I','Senegal','Noruega'),
  ('Fase de grupos','Grupo J','Argentina','Argelia'),('Fase de grupos','Grupo J','Austria','Jordania'),('Fase de grupos','Grupo J','Argentina','Austria'),('Fase de grupos','Grupo J','Jordania','Argelia'),('Fase de grupos','Grupo J','Jordania','Argentina'),('Fase de grupos','Grupo J','Argelia','Austria'),
  ('Fase de grupos','Grupo K','Portugal','Uzbekistan'),('Fase de grupos','Grupo K','Colombia','RD Congo'),('Fase de grupos','Grupo K','Portugal','Colombia'),('Fase de grupos','Grupo K','RD Congo','Uzbekistan'),('Fase de grupos','Grupo K','RD Congo','Portugal'),('Fase de grupos','Grupo K','Uzbekistan','Colombia'),
  ('Fase de grupos','Grupo L','Inglaterra','Croacia'),('Fase de grupos','Grupo L','Ghana','Panama'),('Fase de grupos','Grupo L','Inglaterra','Ghana'),('Fase de grupos','Grupo L','Panama','Croacia'),('Fase de grupos','Grupo L','Panama','Inglaterra'),('Fase de grupos','Grupo L','Croacia','Ghana')
) as v(phase, group_name, team_a, team_b)
on conflict (match_number) do nothing;
